develop:
  addresses:
    - 192.168.100.21
    - 192.168.0.23
    - 192.168.0.46
  api:
    dst-port: 8082
    stop-endpoint: /api/chain/block/mining/stop
    add-block-endpoint: /api/chain/block/add
    get-all-from: /api/chain/block/allafter/
    get-all: /api/chain/block/all
    get-all-utxo: /api/chain/utxo/all
  port: 8888
  serverport: 8888
